# Generated by Django 2.1.1 on 2018-12-03 04:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('subject_area', models.CharField(choices=[('AAS', 'AAS'), ('AMST', 'AMST'), ('ANTH', 'ANTH'), ('APMA', 'APMA'), ('ARAB', 'ARAB'), ('ARAD', 'ARAD'), ('ARCY', 'ARCY'), ('ARTH', 'ARTH'), ('ARTR', 'ARTR'), ('ARTS', 'ARTS'), ('ASL', 'ASL'), ('ASTR', 'ASTR'), ('BIOL', 'BIOL'), ('BME', 'BME'), ('CASS', 'CASS'), ('CHE', 'CHE'), ('CHEM', 'CHEM'), ('CHIN', 'CHIN'), ('CHTR', 'CHTR'), ('CLAS', 'CLAS'), ('COLA', 'COLA'), ('COMM', 'COMM'), ('CPLT', 'CPLT'), ('CS', 'CS'), ('DANC', 'DANC'), ('DRAM', 'DRAM'), ('EALC', 'EALC'), ('EAST', 'EAST'), ('ECE', 'ECE'), ('ECON', 'ECON'), ('EGMT', 'EGMT'), ('ELA', 'ELA'), ('ENAM', 'ENAM'), ('ENCR', 'ENCR'), ('ENCW', 'ENCW'), ('ENEC', 'ENEC'), ('ENGL', 'ENGL'), ('ENGN', 'ENGN'), ('ENLT', 'ENLT'), ('ENMC', 'ENMC'), ('ENMD', 'ENMD'), ('ENNC', 'ENNC'), ('ENPW', 'ENPW'), ('ENRN', 'ENRN'), ('ENSP', 'ENSP'), ('ENWR', 'ENWR'), ('EVSC', 'EVSC'), ('FORU', 'FORU'), ('FREN', 'FREN'), ('FRTR', 'FRTR'), ('GDS', 'GDS'), ('GERM', 'GERM'), ('GETR', 'GETR'), ('GREE', 'GREE'), ('GSGS', 'GSGS'), ('GSSJ', 'GSSJ'), ('GSVS', 'GSVS'), ('HEBR', 'HEBR'), ('HIAF', 'HIAF'), ('HIEA', 'HIEA'), ('HIEU', 'HIEU'), ('HILA', 'HILA'), ('HIND', 'HIND'), ('HISA', 'HISA'), ('HIST', 'HIST'), ('HIUS', 'HIUS'), ('HSCI', 'HSCI'), ('INST', 'INST'), ('ITAL', 'ITAL'), ('ITTR', 'ITTR'), ('JAPN', 'JAPN'), ('JPTR', 'JPTR'), ('JWST', 'JWST'), ('KOR', 'KOR'), ('LASE', 'LASE'), ('LATI', 'LATI'), ('LING', 'LING'), ('LNGS', 'LNGS'), ('MAE', 'MAE'), ('MATH', 'MATH'), ('MDST', 'MDST'), ('MESA', 'MESA'), ('MEST', 'MEST'), ('MSE', 'MSE'), ('MUSI', 'MUSI'), ('PERS', 'PERS'), ('PETR', 'PETR'), ('PHIL', 'PHIL'), ('PHS', 'PHS'), ('PHYS', 'PHYS'), ('PLAP\xa0', 'PLAP\xa0'), ('PLCP\xa0', 'PLCP\xa0'), ('PLIR\xa0', 'PLIR\xa0'), ('PLPT', 'PLPT'), ('POL', 'POL'), ('PORT', 'PORT'), ('POTR', 'POTR'), ('PPL', 'PPL'), ('PSYC', 'PSYC'), ('RELA', 'RELA'), ('RELB', 'RELB'), ('RELC', 'RELC'), ('RELG', 'RELG'), ('RELH', 'RELH'), ('RELI', 'RELI'), ('RELJ', 'RELJ'), ('RELS', 'RELS'), ('RUSS', 'RUSS'), ('RUTR', 'RUTR'), ('SANS', 'SANS'), ('SAST', 'SAST'), ('SATR', 'SATR'), ('SLAV', 'SLAV'), ('SLFK', 'SLFK'), ('SLTR', 'SLTR'), ('SOC', 'SOC'), ('SPAN', 'SPAN'), ('SPTR', 'SPTR'), ('STAT', 'STAT'), ('SYS', 'SYS'), ('TBTN', 'TBTN'), ('URDU', 'URDU'), ('USEM', 'USEM'), ('WGS', 'WGS'), ('YIDD', 'YIDD')], max_length=4)),
                ('class_assoc', models.CharField(max_length=4, verbose_name='Course Number')),
                ('iSBN', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact', models.CharField(max_length=100)),
                ('rent_buy', models.CharField(choices=[('B', 'Buy'), ('R', 'Rent')], max_length=4)),
                ('image', models.ImageField(default='images/default/book_test.png', upload_to='images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
