# Generated by Django 2.1.1 on 2018-12-03 05:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='iSBN',
            field=models.CharField(help_text="Enter your book's iSBN_13 Please", max_length=200),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Please Enter the Price of You Book in US Dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
