# Generated by Django 2.1.1 on 2018-12-09 03:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook', '0002_auto_20181203_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='book_title',
            field=models.CharField(max_length=100, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='class_assoc',
            field=models.CharField(help_text='Please enter in the course number e.g. 3240 for CS3240', max_length=4, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Please Enter the Price of Your Book in US Dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='posting',
            name='rent_buy',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=4, verbose_name='Rent or Buy'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='subject_area',
            field=models.CharField(choices=[('AAS', 'AAS'), ('AMST', 'AMST'), ('ANTH', 'ANTH'), ('APMA', 'APMA'), ('ARAB', 'ARAB'), ('ARAD', 'ARAD'), ('ARCY', 'ARCY'), ('ARTH', 'ARTH'), ('ARTR', 'ARTR'), ('ARTS', 'ARTS'), ('ASL', 'ASL'), ('ASTR', 'ASTR'), ('BIOL', 'BIOL'), ('BME', 'BME'), ('CASS', 'CASS'), ('CHE', 'CHE'), ('CHEM', 'CHEM'), ('CHIN', 'CHIN'), ('CHTR', 'CHTR'), ('CLAS', 'CLAS'), ('COLA', 'COLA'), ('COMM', 'COMM'), ('CPLT', 'CPLT'), ('CS', 'CS'), ('DANC', 'DANC'), ('DRAM', 'DRAM'), ('EALC', 'EALC'), ('EAST', 'EAST'), ('ECE', 'ECE'), ('ECON', 'ECON'), ('EGMT', 'EGMT'), ('ELA', 'ELA'), ('ENAM', 'ENAM'), ('ENCR', 'ENCR'), ('ENCW', 'ENCW'), ('ENEC', 'ENEC'), ('ENGL', 'ENGL'), ('ENGN', 'ENGN'), ('ENLT', 'ENLT'), ('ENMC', 'ENMC'), ('ENMD', 'ENMD'), ('ENNC', 'ENNC'), ('ENPW', 'ENPW'), ('ENRN', 'ENRN'), ('ENSP', 'ENSP'), ('ENWR', 'ENWR'), ('EVSC', 'EVSC'), ('FORU', 'FORU'), ('FREN', 'FREN'), ('FRTR', 'FRTR'), ('GDS', 'GDS'), ('GERM', 'GERM'), ('GETR', 'GETR'), ('GREE', 'GREE'), ('GSGS', 'GSGS'), ('GSSJ', 'GSSJ'), ('GSVS', 'GSVS'), ('HEBR', 'HEBR'), ('HIAF', 'HIAF'), ('HIEA', 'HIEA'), ('HIEU', 'HIEU'), ('HILA', 'HILA'), ('HIND', 'HIND'), ('HISA', 'HISA'), ('HIST', 'HIST'), ('HIUS', 'HIUS'), ('HSCI', 'HSCI'), ('INST', 'INST'), ('ITAL', 'ITAL'), ('ITTR', 'ITTR'), ('JAPN', 'JAPN'), ('JPTR', 'JPTR'), ('JWST', 'JWST'), ('KOR', 'KOR'), ('LASE', 'LASE'), ('LATI', 'LATI'), ('LING', 'LING'), ('LNGS', 'LNGS'), ('MAE', 'MAE'), ('MATH', 'MATH'), ('MDST', 'MDST'), ('MESA', 'MESA'), ('MEST', 'MEST'), ('MSE', 'MSE'), ('MUSI', 'MUSI'), ('PERS', 'PERS'), ('PETR', 'PETR'), ('PHIL', 'PHIL'), ('PHS', 'PHS'), ('PHYS', 'PHYS'), ('PLAP\xa0', 'PLAP\xa0'), ('PLCP\xa0', 'PLCP\xa0'), ('PLIR\xa0', 'PLIR\xa0'), ('PLPT', 'PLPT'), ('POL', 'POL'), ('PORT', 'PORT'), ('POTR', 'POTR'), ('PPL', 'PPL'), ('PSYC', 'PSYC'), ('RELA', 'RELA'), ('RELB', 'RELB'), ('RELC', 'RELC'), ('RELG', 'RELG'), ('RELH', 'RELH'), ('RELI', 'RELI'), ('RELJ', 'RELJ'), ('RELS', 'RELS'), ('RUSS', 'RUSS'), ('RUTR', 'RUTR'), ('SANS', 'SANS'), ('SAST', 'SAST'), ('SATR', 'SATR'), ('SLAV', 'SLAV'), ('SLFK', 'SLFK'), ('SLTR', 'SLTR'), ('SOC', 'SOC'), ('SPAN', 'SPAN'), ('SPTR', 'SPTR'), ('STAT', 'STAT'), ('SYS', 'SYS'), ('TBTN', 'TBTN'), ('URDU', 'URDU'), ('USEM', 'USEM'), ('WGS', 'WGS'), ('YIDD', 'YIDD')], max_length=4, verbose_name='Subject Area'),
        ),
    ]
